easy_utilisateur_update:
    pattern:  /espace-membre/profil/modifier
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:update }
    
easy_utilisateur_profil:
    pattern:  /espace-membre/profil/{username}
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:show }
    
easy_utilisateur_admin:
    pattern:  /administration/utilisateurs
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:listAdmin }
    
easy_utilisateur_delete:
    pattern:  /administration/utilisateurs/supprimer/{username}
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:deleteAdmin }

easy_utilisateur_show_admin:
    pattern:  /administration/utilisateur/modifier/{username}
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:showAdmin } 

easy_utilisateur_add:
    pattern:  /administration/utilisateur/ajouter
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:showAdmin }

easy_utilisateur_update_admin:
    pattern:  /administration/utilisateur/modifier
    defaults: { _controller: EasyUtilisateurBundle:Utilisateur:updateAdmin }
