parameters:
#    easy_utilisateur.example.class: Easy\UtilisateurBundle\Example

services:
#    easy_utilisateur.example:
#        class: %easy_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
