parameters:
#    easy_site.example.class: Easy\SiteBundle\Example

services:
#    easy_site.example:
#        class: %easy_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
