easy_forum_index:
    pattern:  /forum
    defaults: { _controller: EasyForumBundle:Forum:index }

easy_forum_admin:
    pattern:  /administration/forum
    defaults: { _controller: EasyForumBundle:Forum:listAdmin }