parameters:
#    easy_forum.example.class: Easy\ForumBundle\Example

services:
#    easy_forum.example:
#        class: %easy_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
