easy_don_accueil:
    pattern:  /espace-membre/dons
    defaults: { _controller: EasyDonBundle:Don:index }
    
easy_don_tableau:
    pattern:  /espace-membre/dons/tableau-recapitulatif
    defaults: { _controller: EasyDonBundle:Don:list }

easy_don_ajouter:
    pattern:  /espace-membre/dons/ajouter
    defaults: { _controller: EasyDonBundle:Don:add }