parameters:
#    easy_don.example.class: Easy\DonBundle\Example

services:
#    easy_don.example:
#        class: %easy_don.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
