chat_messages_get:
    path:     /chat/messages
    defaults: { _controller: ChatBundle:Messages:getMessages }
    requirements:
        _method: GET
chat_message_new:
    path:     /chat/message
    defaults: { _controller: ChatBundle:Messages:newMessage }
    requirements:
        _method: POST
chat_message_delete:
    path:     /chat/message/{id}
    defaults: { _controller: ChatBundle:Messages:deleteMessage }
    requirements:
        _method: DELETE
chat_message_cancel_delete:
    path:     /chat/message/cancel-delete/{id}
    defaults: { _controller: ChatBundle:Messages:cancelDeleteMessage }
    requirements:
        _method: POST
chat_message_update:
    path:     /chat/message/{id}
    defaults: { _controller: ChatBundle:Messages:updateMessage }
    requirements:
        _method: PUT