parameters:
#    easy_article.example.class: Easy\ArticleBundle\Example

services:
#    easy_article.example:
#        class: %easy_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
