parameters:
#    easy_formation.example.class: Easy\FormationBundle\Example

services:
#    easy_formation.example:
#        class: %easy_formation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
