parameters:
#    easy_dispo.example.class: Easy\DispoBundle\Example

services:
#    easy_dispo.example:
#        class: %easy_dispo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
